### ISSUE TITLE
"Profile" configuration not accessible in "Flutter Build" task

### ISSUE THREAD

**Issue by pwa-tapptic** [hey24sheep/azure-flutter-tasks#32] opened 2022-02-11 14:53 UTC
Hello guys, would it be possible to change a bit build task and add optional configuration dropdown?

Let me explain the problem: currently there is no way to run Flutter Build task with "Profile" configuration. There is only a "Debug" checkbox - if it is checked then Debug configuration is used, otherwise it's Release config. In Flutter projects there is usually "Profile" configuration as well. I'm in a situation where I must use "Profile" one but I have no way to make my Build task doing that.

Proposition:
Replace "Debug" checkbox by "Configuration" dropdown (with three values: Release (IMO it might be default one), Profile, Debug)
Or input field where user can type a name of configuration, but it doesn't seem to be better idea.

**Comment by hey24sheep** [comment] 2022-02-12 12:25
I thnk "profile" can be added but the issue is I don't want to break other people's builds by changing it to to a dropdown. 

I have given "ExtraArgs" input field which exactly for these kind of extensions. If you need a "Profile" flag, you can try to pass "profile" as ["extraArgs"](https://github.com/hey24sheep/azure-flutter-tasks/blob/f6f3044433fd6989aba6c5e0e35222e7cc72180e/tasks/build/task.json#L179) (do not select debug) and push Profile flag here, it should work.

**Comment by pwa-tapptic** [comment] 2022-02-13 06:07
@hey24sheep that's true - changing this means changing the parameters, therefore it would require version 1.* so that pipelines having version 0.* still works.

Anyway, unchecking Debug and adding `--profile` as an extra argument does the job :) 👍 
Thanks!

**Comment by hey24sheep** [comment] 2022-02-13 07:37
Yes, versions will be maintained. But, it depends actually, like in our company it is set to latest. So anytime I make a new feature or edit in this extension and upload to Microsoft marketplace, our pipelines automatically gets updated. 

That extraArgs was added with the same thought in regards to future upgrade without breaking anything. 

I'm glad it's working for you now. I will write it as a feature in future update. For now, I will close this issue as solved with a workaround.

**Closed** 2022-02-13 07:38 UTC
