### ISSUE TITLE
Feature Request - Architecture input parameter for FlutterInstall task

### ISSUE THREAD

**Issue by ctnataman** [hey24sheep/azure-flutter-tasks#44] opened 2022-06-13 12:31 UTC
Hello,

There are now 2 latest stable versions for macos. That's why we should be able to choose one. Could you add "architecture" input parameter to FlutterInstall task?.

https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip
https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.2-stable.zip

```
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'
    architecture: 'arm64'

```

In the file below, the version to be downloaded is selected according to the order in the list. This causes a different arch to be selected each latest version.

For 3.0.2, task will select "stable/macos/flutter_macos_arm64_3.0.2-stable.zip"
For 3.0.1, task will select "stable/macos/flutter_macos_3.0.1-stable.zip"
For 3.0.0, task will select "stable/macos/flutter_macos_3.0.0-stable.zip"

https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json

```
{
  "base_url": "https://storage.googleapis.com/flutter_infra_release/releases",
  "current_release": {
    "beta": "bcea432bce54a83306b3c00a7ad0ed98f777348d",
    "dev": "13a2fb10b838971ce211230f8ffdd094c14af02c",
    "stable": "cd41fdd495f6944ecd3506c21e94c6567b073278"
  },
  "releases": [
    {
      "hash": "cd41fdd495f6944ecd3506c21e94c6567b073278",
      "channel": "stable",
      "version": "3.0.2",
      "dart_sdk_version": "2.17.3",
      "dart_sdk_arch": "arm64",
      "release_date": "2022-06-10T17:11:47.366348Z",
      "archive": "stable/macos/flutter_macos_arm64_3.0.2-stable.zip",
      "sha256": "734874caac4928d86a7bba8aa843e5c0577ccb1051df551db41dd1e4d64b6d9e"
    },
    {
      "hash": "cd41fdd495f6944ecd3506c21e94c6567b073278",
      "channel": "stable",
      "version": "3.0.2",
      "dart_sdk_version": "2.17.3",
      "dart_sdk_arch": "x64",
      "release_date": "2022-06-10T17:02:07.215846Z",
      "archive": "stable/macos/flutter_macos_3.0.2-stable.zip",
      "sha256": "7fc88b2944495c20e013c83c4e0bfcd40d258d9fb52ddbde5c0771e207c9ff29"
    },
    {
      "hash": "bcea432bce54a83306b3c00a7ad0ed98f777348d",
      "channel": "beta",
      "version": "3.1.0",
      "dart_sdk_version": "2.18.0 (build 2.18.0-44.1.beta)",
      "dart_sdk_arch": "x64",
      "release_date": "2022-05-26T17:58:53.645129Z",
      "archive": "beta/macos/flutter_macos_3.1.0-beta.zip",
      "sha256": "8feffb0ef36df30c30aab3ff876578dd2762213e90deee5f3b5847353133fe21"
    },
    {
      "hash": "bcea432bce54a83306b3c00a7ad0ed98f777348d",
      "channel": "beta",
      "version": "3.1.0",
      "dart_sdk_version": "2.18.0 (build 2.18.0-44.1.beta)",
      "dart_sdk_arch": "arm64",
      "release_date": "2022-05-26T17:56:13.705273Z",
      "archive": "beta/macos/flutter_macos_arm64_3.1.0-beta.zip",
      "sha256": "4f4d368dfbc7c6697f2840c434163a9b35dcf5dbe399671513d7ae0e24a0f351"
    },
    {
      "hash": "fb57da5f945d02ef4f98dfd9409a72b7cce74268",
      "channel": "stable",
      "version": "3.0.1",
      "dart_sdk_version": "2.17.1",
      "dart_sdk_arch": "x64",
      "release_date": "2022-05-20T03:38:50.201052Z",
      "archive": "stable/macos/flutter_macos_3.0.1-stable.zip",
      "sha256": "20d96acdc49f877e533697300228b58108b18a970e29184d8477c01889218ce9"
    },
    {
      "hash": "fb57da5f945d02ef4f98dfd9409a72b7cce74268",
      "channel": "stable",
      "version": "3.0.1",
      "dart_sdk_version": "2.17.1",
      "dart_sdk_arch": "arm64",
      "release_date": "2022-05-20T03:35:17.480893Z",
      "archive": "stable/macos/flutter_macos_arm64_3.0.1-stable.zip",
      "sha256": "f34e34f8cf247d4f6fde3f7e9e6753d15ff7f6e88bda232df13c009514896163"
    },
    {
      "hash": "ee4e09cce01d6f2d7f4baebd247fde02e5008851",
      "channel": "stable",
      "version": "3.0.0",
      "dart_sdk_version": "2.17.0",
      "dart_sdk_arch": "x64",
      "release_date": "2022-05-11T18:45:17.043391Z",
      "archive": "stable/macos/flutter_macos_3.0.0-stable.zip",
      "sha256": "63ed2a514c7212baa784a9dd72d5fe6a0bdec690ee0f308721fe03729ab4c9b8"
    },
    {
      "hash": "ee4e09cce01d6f2d7f4baebd247fde02e5008851",
      "channel": "stable",
      "version": "3.0.0",
      "dart_sdk_version": "2.17.0",
      "dart_sdk_arch": "arm64",
      "release_date": "2022-05-11T18:41:27.214347Z",
      "archive": "stable/macos/flutter_macos_arm64_3.0.0-stable.zip",
      "sha256": "128f0fff720541332c52f289f8cb77e679a32e8a617ace54273def902d00e02d"
    },
   ...
}
```

**Comment by kiratheone** [comment] 2022-06-15 06:51
I think this PR https://github.com/hey24sheep/azure-flutter-tasks/pull/45 use good approach. It will find your agent architecture automatically and download the correct one.

**Comment by hey24sheep** [comment] 2022-06-15 12:14
@kiratheone I totally missed the "os.arch" I will merge and code the rest.

**Comment by hey24sheep** [comment] 2022-06-15 12:52
I have updated the extension, it should be available within 15 minutes or so. Let me know if it is working as intended by closing this issue.

**Closed as completed** 2022-06-15 13:37 UTC
Labels: enhancement

**Comment by hey24sheep** [comment] 2022-06-15 15:14
@ctnataman @kiratheone 👍🏻 Good to hear that, thank you for testing it.
