### ISSUE TITLE
Flutter Commands failing w/Flutter 3.0.2

### ISSUE THREAD

**Issue by bobwiller** [hey24sheep/azure-flutter-tasks#43] opened 2022-06-10 19:07 UTC
We have a pipeline that has been running fine for a long time.  Today they broke, with the following error:
```

Starting: FlutterCommand
==============================================================================
Task         : Flutter Command Task
Description  : Launch a custom Flutter command with custom arguments.
Version      : 0.3.0
Author       : Hey24sheep
Help         : Don't forget to insert a 'Flutter Install' task before. [More Information](https://github.com/hey24sheep/azure-flutter-tasks)
==============================================================================
/Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/flutter pub run intl_utils:generate
/Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/internal/shared.sh: line 225: /Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/cache/dart-sdk/bin/dart: Bad CPU type in executable
##[error]Error: The process '/Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos/flutter/bin/flutter' failed with exit code 1
Finishing: FlutterCommand

```
Looks like it is related to Flutter 3.0.2.  Manually setting the Flutter version back to 3.0.1 fixes the issue.

**Comment by tghamm** [comment] 2022-06-10 22:12
I ran into the same thing just a couple of hours ago.  A rollback to 3.0.1 seems to address the issue for me as well.

**Comment by hey24sheep** [comment] 2022-06-11 02:57
Looking at the log it is because of "Bad CPU Type", which is an Apple / Flutter issue.

Here is the solution to [this](https://github.com/flutter/flutter/issues/74511). Also, check these links [Reddit1](https://www.reddit.com/r/flutterhelp/comments/u3hzyo/bad_cpu_type_in_executable_when_trying_to_run/) and [Reddit2](https://www.reddit.com/r/flutterhelp/comments/kh7w5n/how_to_run_flutter_on_apples_m1_arm/).

**Comment by ctnataman** [comment] 2022-06-11 08:32
There are now 2 latest stable versions. That's why we should be able to choose one. Could you add "architecture" input parameter to FlutterInstall task?.

https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip
https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.2-stable.zip

```
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'
    architecture: 'arm64'

```

```
{
  "base_url": "https://storage.googleapis.com/flutter_infra_release/releases",
  "current_release": {
    "beta": "bcea432bce54a83306b3c00a7ad0ed98f777348d",
    "dev": "13a2fb10b838971ce211230f8ffdd094c14af02c",
    "stable": "cd41fdd495f6944ecd3506c21e94c6567b073278"
  },
  "releases": [
    {
      "hash": "cd41fdd495f6944ecd3506c21e94c6567b073278",
      "channel": "stable",
      "version": "3.0.2",
      "dart_sdk_version": "2.17.3",
      "dart_sdk_arch": "arm64",
      "release_date": "2022-06-10T17:11:47.366348Z",
      "archive": "stable/macos/flutter_macos_arm64_3.0.2-stable.zip",
      "sha256": "734874caac4928d86a7bba8aa843e5c0577ccb1051df551db41dd1e4d64b6d9e"
    },
    {
      "hash": "cd41fdd495f6944ecd3506c21e94c6567b073278",
      "channel": "stable",
      "version": "3.0.2",
      "dart_sdk_version": "2.17.3",
      "dart_sdk_arch": "x64",
      "release_date": "2022-06-10T17:02:07.215846Z",
      "archive": "stable/macos/flutter_macos_3.0.2-stable.zip",
      "sha256": "7fc88b2944495c20e013c83c4e0bfcd40d258d9fb52ddbde5c0771e207c9ff29"
    },
    {
      "hash": "bcea432bce54a83306b3c00a7ad0ed98f777348d",
      "channel": "beta",
      "version": "3.1.0",
      "dart_sdk_version": "2.18.0 (build 2.18.0-44.1.beta)",
      "dart_sdk_arch": "x64",
      "release_date": "2022-05-26T17:58:53.645129Z",
      "archive": "beta/macos/flutter_macos_3.1.0-beta.zip",
      "sha256": "8feffb0ef36df30c30aab3ff876578dd2762213e90deee5f3b5847353133fe21"
    },
    {
      "hash": "bcea432bce54a83306b3c00a7ad0ed98f777348d",
      "channel": "beta",
      "version": "3.1.0",
      "dart_sdk_version": "2.18.0 (build 2.18.0-44.1.beta)",
      "dart_sdk_arch": "arm64",
      "release_date": "2022-05-26T17:56:13.705273Z",
      "archive": "beta/macos/flutter_macos_arm64_3.1.0-beta.zip",
      "sha256": "4f4d368dfbc7c6697f2840c434163a9b35dcf5dbe399671513d7ae0e24a0f351"
    },
    {
      "hash": "fb57da5f945d02ef4f98dfd9409a72b7cce74268",
      "channel": "stable",
      "version": "3.0.1",
      "dart_sdk_version": "2.17.1",
      "dart_sdk_arch": "x64",
      "release_date": "2022-05-20T03:38:50.201052Z",
      "archive": "stable/macos/flutter_macos_3.0.1-stable.zip",
      "sha256": "20d96acdc49f877e533697300228b58108b18a970e29184d8477c01889218ce9"
    },
   ...
}
```

**Comment by bobwiller** [comment] 2022-06-11 13:24
@hey24sheep this is the error I get from devops when I try to install rosetta:

"Installing Rosetta 2 on this system is not supported."

Any thoughts about how to (or if you can) add this step to a pipeline?

**Comment by hey24sheep** [comment] 2022-06-12 14:12
@ctnataman could you add that to a new issue. It's a feature request different to the current issue.

**Comment by hey24sheep** [comment] 2022-06-12 14:17
@bobwiller Are you running the command on the latest MacOs VM Agent?

I can't seem to find anything else related to this particular error log. Could you run your Flutter command with verbose and paste the full log here. If verbose log doesn't give much more info, you could also open this same issue on Flutter's Github, maybe someone from Flutter teams knows about the solution.

**Comment by bobwiller** [comment] 2022-06-12 16:08
Yes, vmImage: macOS-latest

I guess maybe I am confused - installing rosetta isn't a Flutter command.  In my pipeline I added this after the FlutterInstall task:

- task: CmdLine@2
  inputs:
    script: 'softwareupdate --install-rosetta'

Here is the entire output:
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
softwareupdate --install-rosetta
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/28d2bbb4-b0f3-4a1d-9029-e3e56ce0cf9a.sh
Installing Rosetta 2 on this system is not supported.
##[error]Bash exited with code '1'.
Finishing: CmdLine

If you want me to try something different let me know.

**Comment by hey24sheep** [comment] 2022-06-12 17:41
@bobwiller I don't think this will work. Problem is from Microsoft's or Flutter's side. 

First, I would recommend you to create this issue on [Flutter's Github](https://github.com/flutter/flutter). This will be more helpful. Someone could point you in the right direction.

Second, check this [link](https://itnext.io/run-azure-self-hosted-macos-agents-on-apple-m1-mac-72726555d83b). You can currently use a self hosted agent to bypass the builds so this way you won't be stuck.

**Comment by kostadin-damyanov-prime** [comment] 2022-06-14 08:18
@hey24sheep I think the problem is with the Install task downloading `arm64` binaries on `x86-64` agents.
We can modify it to check the platform before downloading flutter.

You can exec `uname -m` to check this. It returns `arm64` on M1 macs and `x86_64` on intels (according to [this](https://stackoverflow.com/a/65259353) SO post). Then you will know which one to download from @ctnataman json example above.

**Comment by hey24sheep** [comment] 2022-06-15 12:52
I have updated the extension, it should be available within 15 minutes or so. Let me know if it is working as intended by closing this issue.

**Comment by hey24sheep** [comment] 2022-06-15 17:39
@bobwiller I have updated the extension twice today, it should be available within 15 minutes or so. Let me know if it is working as intended by closing this issue. Else, this issue will be closed within few weeks as obsolete.

**Comment by kostadin-damyanov-prime** [comment] 2022-06-16 06:57
I still got the "Bad CPU type in executable" error on MS-hosted MacOS agents and Flutter version 3.0.2.
Flutter Install Task version is `0.3.2` and it downloaded [flutter_macos_arm64_3.0.2-stable.zip](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip).

**Comment by hey24sheep** [comment] 2022-06-17 06:19
@kostadin-damyanov-prime It auto detects the arch type and then downloads the sdk. If you try to give it a customArchType it can download that. It should work without any issues as it has been tested live and otherwise. 

You can check if you are on the latest extension or not. Also could you post verbose logs here of the same along with your config.

**Comment by kostadin-damyanov-prime** [comment] 2022-06-17 07:44
@hey24sheep I ran the pipeline with system diagnostics enabled and this is the output:

```
##[debug]Finding version 'custom' from 'https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json'
##[debug]customArch=undefined
##[debug]Using Arch type 'x64'
##[debug]customVersion=3.0.2
##[debug]Found version hash 'cd41fdd495f6944ecd3506c21e94c6567b073278'
##[debug]Trying to get (Flutter,3.0.2-stable, macos) tool from local cache
##[debug]isExplicit: 3.0.2-stable
##[debug]explicit? true
##[debug]Agent.Version=2.204.0
##[debug]Agent.ToolsDirectory=/Users/runner/hostedtoolcache
##[debug]checking cache: /Users/runner/hostedtoolcache/Flutter/3.0.2-stable/macos
##[debug]not found
##[debug]Starting download archive from 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip'
##[debug]
##[debug]Agent.Version=2.204.0
##[debug]Agent.TempDirectory=/Users/runner/work/_temp
##[debug]testing directory '/Users/runner/work/_temp'
Downloading: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip
##[debug]destination /Users/runner/work/_temp/c5c91659-76bb-4d4c-9033-0883716ba772
##[debug]downloading
##[debug]creating stream
##[debug]download complete
##[debug]Succeeded to download '/Users/runner/work/_temp/c5c91659-76bb-4d4c-9033-0883716ba772' archive from 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip'
##[debug]Extracting 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_3.0.2-stable.zip' archive
Extracting archive
```

It resolves the arch to `x64` and somehow still downloads `arm64`. How this could happen?

**Comment by hey24sheep** [comment] 2022-06-17 09:21
@kostadin-damyanov-prime it is indeed weird. I ran some tests and I cannot reproduce the shown result :/

Here are my tests, with x64
![Capture](https://user-images.githubusercontent.com/31468022/174268534-0496ce85-bef1-47b8-833e-07b5aed89dfd.PNG)

with arm64
![Capture1](https://user-images.githubusercontent.com/31468022/174268573-c10ffd52-5fed-4997-b722-5430530c9fab.PNG)

Could you try giving it a `customArch` value as 'x64' and check if it builds successfully.

**Comment by kostadin-damyanov-prime** [comment] 2022-06-17 10:30
I am not using the `customArch` parameter. We are using MS-hosted agents and I do not know if all of them are x64.
However, I think I found what the issue is. It happens when I provide a specific version but not a customArch.

```
// if user selected custom
if (version.toLowerCase() !== 'latest') {
	// fetch custom version
	version = task.getInput('customVersion', false);

	if (customArch && customArch.trim() !== '') {
		current = json.releases.find((item) => item.channel == channel && uniformizeVersion(item.version) == uniformizeVersion(version) && item.dart_sdk_arch == customArch);
	} else {
		current = json.releases.find((item) => item.channel == channel && uniformizeVersion(item.version) == uniformizeVersion(version));
	}
}

```

I think in the `else` block we should add `&& item.dart_sdk_arch == arch` so that it will use the detected arch value.

**Comment by hey24sheep** [comment] 2022-06-17 11:54
@kostadin-damyanov-prime I see, I wanted to keep all builds intact. 

So think of this, there are 3 kind of releases now, 
1 - old releases which are missing this new arch type key in json
2 - new releases which has this key in json
3 - which has 2 different values for the same key (only on macos (bane of my existence :D)

So, I assumed that people will bypass this error automatically by providing it a `customArch` if they read logs. But, you are not wrong here as well. It is hard to debug and know what is wrong. 

I have just pushed a new fix which will auto check for all these three scenarios I have mentioed above. It should be available in 15 minutes or so. I have tested locally it works as intented but please check on your agents too and let me know.

**Comment by kostadin-damyanov-prime** [comment] 2022-06-17 12:30
The latest update fixed the issue for me, thanks @hey24sheep!

**Comment by hey24sheep** [comment] 2022-06-17 12:32
I am closing this issue as considered fix by multiple latest updates. If anyone faces any issues, feel free to open up a new one.

**Closed by hey24sheep** 2022-06-17 12:32 UTC
Labels: help wanted
