### ISSUE TITLE
Warnings in flutter build task: Use Cipheriv for counter mode of aes-256-ctr

### ISSUE THREAD

**Issue by patspaeth** [hey24sheep/azure-flutter-tasks#20] opened 2021-10-20 13:35 UTC
Flutter Build Task Warnings:
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1654) Warning: Use Cipheriv for counter mode of aes-256-ctr

Please refer to https://github.com/microsoft/azure-pipelines-tasks/issues/12147
It seems that this will be fixed with the version of the task-lib ^2.9.0

**Comment by hey24sheep** [comment] 2021-11-13 09:30
@patspaeth I have checked on my latest build, the warning are no longer shown. I am closing this issue. 

If warnings are still shown on your pipeline, let me know I will reopen this issue.

You can track the changes [here](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/CHANGELOG.md).

**Closed by hey24sheep** 2021-11-13 09:30 UTC
Labels: 3rd-party-issue

**Comment by Bengkel** [comment] 2021-12-08 18:23
The warnings show on our pipeline, so probably the issue is not fixed.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/6442129/145262859-25db9774-1621-4eff-9807-5a06a32f4ae6.png">

**Comment by hey24sheep** [comment] 2021-12-09 00:49
> The warnings show on our pipeline, so probably the issue is not fixed.
> 
> <img width="575" alt="image" src="https://user-images.githubusercontent.com/6442129/145262859-25db9774-1621-4eff-9807-5a06a32f4ae6.png">
> 

The cmd task that you are showing is developed by "Microsoft". It has nothing to do with this Extension.
