### ISSUE TITLE
Target file "--no-sound-null-safety --no-tree-shake-icons" not found.

### ISSUE THREAD

**Issue by eric2788** [hey24sheep/azure-flutter-tasks#93] opened 2023-07-24 02:42 UTC
```yaml
- task: FlutterBuild@0
   inputs:
      target: 'mobile'
      projectDirectory: '.'
      buildNumber: '$(BUILD_NUM)'
      buildName: '$(VERSION)'
      extraArgs: '--no-sound-null-safety --no-tree-shake-icons'
      apkTargetPlatform: 'android-arm64'
      iosCodesign: false
```

got
 
```bash
Target file "--no-sound-null-safety --no-tree-shake-icons" not found.
```

downgraded to 0.3.6 solve the problem.

**Comment by hey24sheep** [comment] 2023-07-24 07:35
Hi, thank you for logging the issue. I gather the latest changes created this bug.

Please give me a little time to fix it. I'll fix it at the earliest.

**Comment by khalilyamoun** [comment] 2023-07-24 11:04
Flavors are also broken...
Target file " lib/production.dart" not found.

**Comment by Mslamah** [comment] 2023-07-24 11:46
We are also facing issue with flavors
Target file "--target lib/main_development.dart --flavor development" not found.

**Comment by hey24sheep** [comment] 2023-07-24 12:40
@khalilyamoun @Mslamah Yes, I know. I will try to push a fix today after work.

**Comment by baris-yldrm** [comment] 2023-07-24 13:09
same error when we pass extra command like below. It is working when we send only one extra command. Also it is working we run the build task directly from  terminal manually.
"Target file "--no-tree-shake-icons  --obfuscate --split-debug-info=./build/app/outputs/symbols --verbose" not found."

I changed build task to command task for workaround. 

@hey24sheep  thank you for your work.

**Comment by hey24sheep** [comment] 2023-07-24 15:49
Hi all, I have updated the extension to `0.3.14` it introduces a new `separator` input param to fix the multiple arguments or multiple dart defines (containing whitespace within values). Please check the readme & changelogs for further details.

Builds must be fixed now, please let me know by closing your respective issues, thank you all.

**Comment by nick-gallimore** [comment] 2023-07-24 22:50
Thanks for the fix, we were affected by this as well.

Unfortunately, it looks like `buildWeb` is broken (but different). All of the arguments are doubled-up. The split-by-separator lines were uncommented and adjusted, but the previous line that adds the extra args as a single string (`args.push(extraArgs.trim());`) was left as well. I've only checked `buildWeb` as that's the one we're using, not sure if the same problem is in any of the other targets.

Thanks.

**Comment by eric2788** [comment] 2023-07-25 01:49
Not sure if there is a delay here..... when I tried to use ``FlutterBuild@0`` it downloaded 0.3.8 for me (instead of 0.3.14), but it fixed the issue.
This problem was caused from 0.3.7 (got this version while using``FlutterBuild@0`` as task)
<img width="644" alt="image" src="https://github.com/hey24sheep/azure-flutter-tasks/assets/6276840/6149af2d-4906-4a99-8433-0590e55a1720">
Anyway I think this issue could be closed now

**Comment by hey24sheep** [comment] 2023-07-25 06:32
@nick-gallimore Your issue must fixed now, I have updated the extension with that build fix `0.3.15`

**Comment by hey24sheep** [comment] 2023-07-25 06:35
@eric2788 Hi, the updates take time sometimes. There is a new update now, so `build task` is now on `0.3.9`. So, all builds must be working now.

You all can test and check your builds. If something is not working fine, comment here and I will try to fix that. Otherwise, I will close this issue within two days of no activity, thanks.

**Comment by Mslamah** [comment] 2023-07-25 12:04
Hi @hey24sheep thank you for the fix. Currently the builds are working fine

**Comment by nick-gallimore** [comment] 2023-07-27 03:09
Thanks for the quick fix, I've just tested and confirmed it's running as expected again.

**Closed** 2023-08-05 10:20 UTC
Labels: new-version-bug
